[package]
name = "dlarm"
version = "0.1.0"
authors = ["Daniel Sockwell <dsockwell@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.32"}
chrono = "0.4.6"
dirs = "1.0.4"
man = "0.1.1"
